services:
  airflow-db:
    image: postgres:15
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 20

  pipeline-db:
    image: postgres:15
    container_name: pipeline-db
    environment:
      POSTGRES_USER: pipeline
      POSTGRES_PASSWORD: pipeline
      POSTGRES_DB: pipeline
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pipeline -d pipeline"]
      interval: 5s
      timeout: 5s
      retries: 20

  airflow-init:
    image: ads507-airflow:2.8.4
    build:
      context: .
      dockerfile: docker/Dockerfile.airflow
    container_name: airflow-init
    depends_on:
      airflow-db:
        condition: service_healthy
      pipeline-db:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow

      PIPE_DB_HOST: pipeline-db
      PIPE_DB_PORT: "5432"
      PIPE_DB_NAME: pipeline
      PIPE_DB_USER: pipeline
      PIPE_DB_PASSWORD: pipeline

      PYTHONPATH: /opt/airflow:/opt/airflow/etl
    volumes:
      - ./airflow:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
    command: >
      bash -lc "airflow db migrate &&
      (airflow users create
      --username admin
      --password admin
      --firstname Mason
      --lastname Delan
      --role Admin
      --email admin@example.com || true)"
    restart: "no"

  airflow-webserver:
    image: ads507-airflow:2.8.4
    build:
      context: .
      dockerfile: docker/Dockerfile.airflow
    container_name: airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      airflow-db:
        condition: service_healthy
      pipeline-db:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow

      PIPE_DB_HOST: pipeline-db
      PIPE_DB_PORT: "5432"
      PIPE_DB_NAME: pipeline
      PIPE_DB_USER: pipeline
      PIPE_DB_PASSWORD: pipeline

      PYTHONPATH: /opt/airflow:/opt/airflow/etl
    volumes:
      - ./airflow:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
    ports:
      - "8080:8080"
    command: webserver
    restart: always

  airflow-scheduler:
    image: ads507-airflow:2.8.4
    build:
      context: .
      dockerfile: docker/Dockerfile.airflow
    container_name: airflow-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      airflow-db:
        condition: service_healthy
      pipeline-db:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow

      PIPE_DB_HOST: pipeline-db
      PIPE_DB_PORT: "5432"
      PIPE_DB_NAME: pipeline
      PIPE_DB_USER: pipeline
      PIPE_DB_PASSWORD: pipeline

      PYTHONPATH: /opt/airflow:/opt/airflow/etl
    volumes:
      - ./airflow:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
    command: scheduler
    restart: always
